CREATE TABLE `joining_kit_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`fathersName` varchar(255) NOT NULL,
	`mothersName` varchar(255),
	`spouseName` varchar(255),
	`dateOfBirth` varchar(20) NOT NULL,
	`gender` varchar(50) NOT NULL,
	`maritalStatus` varchar(50) NOT NULL,
	`nationality` varchar(100),
	`bloodGroup` varchar(10),
	`religion` varchar(100),
	`currentAddress` text NOT NULL,
	`currentLandmark` varchar(255),
	`permanentAddress` text,
	`village` varchar(255),
	`state` varchar(100),
	`mobileNumber` varchar(20) NOT NULL,
	`landline` varchar(20),
	`personalEmail` varchar(320) NOT NULL,
	`placeOfSigning` varchar(255),
	`employeeId` varchar(50) NOT NULL,
	`designation` varchar(255) NOT NULL,
	`department` varchar(255) NOT NULL,
	`reportingManager` varchar(255) NOT NULL,
	`dateOfJoining` varchar(20) NOT NULL,
	`employmentType` varchar(50) NOT NULL,
	`workLocation` varchar(255) NOT NULL,
	`ctc` varchar(50),
	`officeEmail` varchar(320),
	`panNumber` varchar(20) NOT NULL,
	`aadhaarNumber` varchar(20) NOT NULL,
	`bankAccountNumber` varchar(50) NOT NULL,
	`bankName` varchar(255) NOT NULL,
	`ifscCode` varchar(20) NOT NULL,
	`accountHolderName` varchar(255) NOT NULL,
	`emergencyContactName` varchar(255) NOT NULL,
	`emergencyContactRelation` varchar(100) NOT NULL,
	`emergencyContactPhone` varchar(20) NOT NULL,
	`pfNumber` varchar(50),
	`esiNumber` varchar(50),
	`dependents` int DEFAULT 0,
	`signature` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`submittedBy` int,
	`status` enum('draft','submitted','reviewed','approved') NOT NULL DEFAULT 'submitted',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `joining_kit_submissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `joining_kit_submissions_employeeId_unique` UNIQUE(`employeeId`)
);
